# Generated by Django 2.2 on 2019-04-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superheroe',
            name='bio',
            field=models.CharField(default='hola', max_length=500),
            preserve_default=False,
        ),
    ]
